language: node_js
node_js:
  - "11"
  - "10"
  - "8"
  - "6"

env:
  global:
    - CC_TEST_REPORTER_ID=3d12bcb4e049108629f1fbf5c33b318c36f49035b11df575b990459a8c849e4e

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

script:
    - npm run lint
    - npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
